# Install requirements

In [1]:
%pip install pymupdf
%pip install pandas
%pip install tiktoken
%pip install sentence-transformers
%pip install pyarrow # for Parquet support
%pip install numpy
%pip install langchain
%pip install langchain-community
%pip install -U langchain-huggingface # for depreciation warning
%pip install rank_bm25
%pip install faiss-cpu
%pip install ragas
%pip install rapidfuzz
%pip install langchain_groq
%pip install openai

Requirement already satisfied: pymupdf in ./.venv/lib/python3.13/site-packages (1.26.4)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.13/site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: tiktoken in ./.venv/lib/python3.13/site-packages (0.11.0)
Requirement already satisfied: regex>=2022.1.18 in ./.venv/lib/python3.13/site-packages (from tiktoken) (2025.9.18)
Requirement already satisfied: requests>=2.26.0 in ./.venv/lib/python3.13/site-packages (from tiktoken) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests>=2.26.0->tiktoken) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.13/site-packages (from requests>=2.26.0->tiktoken) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.13/site-packages (from requests>=2.26.0->tiktoken) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.13/site-packages (from requests>=2.26.0->tiktoken) (2025.8.3)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: sentence-transformers in ./.venv/lib/python3.13/site-packages (5.1.1)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in ./.venv/lib/python3.13/site-packages (from sentence-transformers) (4.56.2)
Requirement already satisfied: tqdm in ./.venv/lib/python3.13/site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in ./.venv/lib/python3.13/site-packages (from sentence-transformers) (2.8.0)
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.13/site-packages (from sentence-transformers) (1.7.2)
Requirement already satisfied: scipy in ./.venv/lib/python3.13/site-packages (from sentence-transformers) (1.16.2)
Requirement already satisfied: huggingface-hub>=0.20.0 in ./.venv/lib/python3.13/site-packages (from sentence-transformers) (0.35.1)
Requirement already satisfied: Pillow in ./.venv/lib/python3.13/site-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in ./.venv/lib/python3.13/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in ./.venv/lib/python3.13/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.19.1)
Requirement already satisfied: numpy>=1.17 in ./.venv/lib/python3.13/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.3.3)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.13/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./.venv/lib/python3.13/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in ./.venv/lib/python3.13/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.9.18)
Requirement already satisfied: requests in ./.venv/lib/python3.13/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./.venv/lib/python3.13/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in ./.venv/lib/python3.13/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in ./.venv/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./.venv/lib/python3.13/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.10)
Requirement already satisfied: setuptools in ./.venv/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in ./.venv/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx in ./.venv/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.13/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./.venv/lib/python3.13/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.13/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.13/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.13/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.13/site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.8.3)
Requirement already satisfied: joblib>=1.2.0 in ./.venv/lib/python3.13/site-packages (from scikit-learn->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./.venv/lib/python3.13/site-packages (from scikit-learn->sentence-transformers) (3.6.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pyarrow in ./.venv/lib/python3.13/site-packages (21.0.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in ./.venv/lib/python3.13/site-packages (2.3.3)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: langchain in ./.venv/lib/python3.13/site-packages (0.3.27)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.72 in ./.venv/lib/python3.13/site-packages (from langchain) (0.3.76)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in ./.venv/lib/python3.13/site-packages (from langchain) (0.3.11)
Requirement already satisfied: langsmith>=0.1.17 in ./.venv/lib/python3.13/site-packages (from langchain) (0.4.30)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in ./.venv/lib/python3.13/site-packages (from langchain) (2.11.9)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in ./.venv/lib/python3.13/site-packages (from langchain) (2.0.43)
Requirement already satisfied: requests<3,>=2 in ./.venv/lib/python3.13/site-packages (from langchain) (2.32.5)
Requirement already satisfied: PyYAML>=5.3 in ./.venv/lib/python3.13/site-packages (from langchain) (6.0.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in ./.venv/lib/python3.13/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (9.1.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in ./.venv/lib/python3.13/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (1.33)
Requirement already satisfied: typing-extensions>=4.7 in ./.venv/lib/python3.13/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (4.15.0)
Requirement already satisfied: packaging>=23.2 in ./.venv/lib/python3.13/site-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (25.0)
Requirement already satisfied: jsonpointer>=1.9 in ./.venv/lib/python3.13/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.72->langchain) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in ./.venv/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in ./.venv/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2->langchain) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2->langchain) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2->langchain) (2025.8.3)
Requirement already satisfied: httpx<1,>=0.23.0 in ./.venv/lib/python3.13/site-packages (from langsmith>=0.1.17->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in ./.venv/lib/python3.13/site-packages (from langsmith>=0.1.17->langchain) (3.11.3)
Requirement already satisfied: requests-toolbelt>=1.0.0 in ./.venv/lib/python3.13/site-packages (from langsmith>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in ./.venv/lib/python3.13/site-packages (from langsmith>=0.1.17->langchain) (0.25.0)
Requirement already satisfied: anyio in ./.venv/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (4.11.0)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in ./.venv/lib/python3.13/site-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (1.3.1)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: langchain-community in ./.venv/lib/python3.13/site-packages (0.3.29)
Requirement already satisfied: langchain-core<2.0.0,>=0.3.75 in ./.venv/lib/python3.13/site-packages (from langchain-community) (0.3.76)
Requirement already satisfied: langchain<2.0.0,>=0.3.27 in ./.venv/lib/python3.13/site-packages (from langchain-community) (0.3.27)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in ./.venv/lib/python3.13/site-packages (from langchain-community) (2.0.43)
Requirement already satisfied: requests<3,>=2.32.5 in ./.venv/lib/python3.13/site-packages (from langchain-community) (2.32.5)
Requirement already satisfied: PyYAML>=5.3 in ./.venv/lib/python3.13/site-packages (from langchain-community) (6.0.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in ./.venv/lib/python3.13/site-packages (from langchain-community) (3.12.15)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in ./.venv/lib/python3.13/site-packages (from langchain-community) (9.1.2)
Requirement already satisfied: dataclasses-json<0.7,>=0.6.7 in ./.venv/lib/python3.13/site-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in ./.venv/lib/python3.13/site-packages (from langchain-community) (2.11.0)
Requirement already satisfied: langsmith>=0.1.125 in ./.venv/lib/python3.13/site-packages (from langchain-community) (0.4.30)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in ./.venv/lib/python3.13/site-packages (from langchain-community) (0.4.1)
Requirement already satisfied: numpy>=2.1.0 in ./.venv/lib/python3.13/site-packages (from langchain-community) (2.3.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in ./.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in ./.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in ./.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./.venv/lib/python3.13/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.20.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in ./.venv/lib/python3.13/site-packages (from dataclasses-json<0.7,>=0.6.7->langchain-community) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in ./.venv/lib/python3.13/site-packages (from dataclasses-json<0.7,>=0.6.7->langchain-community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in ./.venv/lib/python3.13/site-packages (from langchain<2.0.0,>=0.3.27->langchain-community) (0.3.11)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in ./.venv/lib/python3.13/site-packages (from langchain<2.0.0,>=0.3.27->langchain-community) (2.11.9)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in ./.venv/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.75->langchain-community) (1.33)
Requirement already satisfied: typing-extensions>=4.7 in ./.venv/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.75->langchain-community) (4.15.0)
Requirement already satisfied: packaging>=23.2 in ./.venv/lib/python3.13/site-packages (from langchain-core<2.0.0,>=0.3.75->langchain-community) (25.0)
Requirement already satisfied: jsonpointer>=1.9 in ./.venv/lib/python3.13/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<2.0.0,>=0.3.75->langchain-community) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in ./.venv/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain-community) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in ./.venv/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain-community) (0.4.1)
Requirement already satisfied: python-dotenv>=0.21.0 in ./.venv/lib/python3.13/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2.32.5->langchain-community) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2.32.5->langchain-community) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.13/site-packages (from requests<3,>=2.32.5->langchain-community) (2025.8.3)
Requirement already satisfied: mypy-extensions>=0.3.0 in ./.venv/lib/python3.13/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.6.7->langchain-community) (1.1.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./.venv/lib/python3.13/site-packages (from langsmith>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in ./.venv/lib/python3.13/site-packages (from langsmith>=0.1.125->langchain-community) (3.11.3)
Requirement already satisfied: requests-toolbelt>=1.0.0 in ./.venv/lib/python3.13/site-packages (from langsmith>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in ./.venv/lib/python3.13/site-packages (from langsmith>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: anyio in ./.venv/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.125->langchain-community) (4.11.0)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.13/site-packages (from httpx<1,>=0.23.0->langsmith>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in ./.venv/lib/python3.13/site-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.125->langchain-community) (1.3.1)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: langchain-huggingface in ./.venv/lib/python3.13/site-packages (0.3.1)
Collecting langchain-huggingface
  Downloading langchain_huggingface-1.0.0-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.33.4 in ./.venv/lib/python3.13/site-packages (from langchain-huggingface) (0.35.1)
Collecting langchain-core<2.0.0,>=1.0.0 (from langchain-huggingface)
  Downloading langchain_core-1.0.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in ./.venv/lib/python3.13/site-packages (from langchain-huggingface) (0.22.1)
Requirement already satisfied: filelock in ./.venv/lib/python3.13/site-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain-huggingface) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in ./.venv/lib/python3.13/site-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain-huggingface) (2025.9.0)
Requirement already satisfied: packaging>=20.9 in ./.venv/lib/python3.13/site-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain-huggingface) (25.0)
Requirement already satisfied: pyyaml>=5.1 in ./.venv/lib/python3.13/site-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain-huggingface) (6.0.2)
Requirement already satisfied: requests in ./.venv/lib/python3.13/site-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain-huggingface) (2.32.5)
Requirement already satisfied: tqdm>=4.42.1 in ./.venv/lib/python3.13/site-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain-huggingface) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./.venv/lib/python3.13/site-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain-huggingface) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./.venv/lib/python3.13/site-packages (from huggingface-hub<1.0.0,>=0.33.4->langchain-huggingface) (1.1.10)

In [2]:
import fitz
import pymupdf
import pandas as pd
import os

input_folder = "data/input/"
files = [f for f in os.listdir(input_folder) if f.endswith(".pdf")]
df = pd.DataFrame(columns=["file_name", "text"])

for file in files:
    path = os.path.join(input_folder, file)
    doc = pymupdf.open(path)
    print(f"Processing {file} with {doc.page_count} pages...")
    extracted_text = ""
    for page in doc:
        extracted_text += page.get_text()
    df.loc[df.shape[0]] = {"file_name": file, "text": extracted_text}

# Save to CSV
extracted_text_file = "extracted_text_from_pdfs.csv"
df.to_csv(f"data/output/{extracted_text_file}", index=False)

print(f"Extracted text and saved to {extracted_text_file}")

Processing 20109399_User manual_A1000_en (1).pdf with 92 pages...
Processing 20169320_TUM_SB1200_en.pdf with 88 pages...
Extracted text and saved to extracted_text_from_pdfs.csv

# Step 2: Chunk text with metadata

In [3]:
import tiktoken
import pandas as pd

# Load tokenizer
encoding = tiktoken.encoding_for_model("gpt-3.5-turbo")
print(encoding.name)

# Chunking function
def chunk_text_with_metadata(text, chunk_size=500, overlap=50):
    tokens = encoding.encode(text)
    chunks = []
    start = 0
    chunk_id = 0

    while start < len(tokens):
        end = start + chunk_size
        chunk_tokens = tokens[start:end]
        chunk_text = encoding.decode(chunk_tokens)

        chunks.append({
            "chunk_id": chunk_id,
            "start_token": start,
            "end_token": end,
            "text": chunk_text
        })

        chunk_id += 1
        start += chunk_size - overlap  # sliding window
    return pd.DataFrame(chunks)

def chunk_multi_text_with_metadata(filenames, texts, chunk_size=500, overlap=50):
    assert len(filenames) == len(texts), "length of filenames must match length of texts"
    chunk_df_lst = []
    for i in range(len(texts)):
        chunk_df = chunk_text_with_metadata(texts[i], chunk_size, overlap)
        chunk_df["chunk_id"] = chunk_df["chunk_id"].apply(lambda x: f"{filenames[i]}_{x:04d}")
        chunk_df_lst.append(chunk_df)
    return pd.concat(chunk_df_lst, ignore_index=True)

chunk_df = chunk_multi_text_with_metadata(df["file_name"], df["text"])

chunked_pdf_text_file = "data/output/chunked_pdf_text.csv"
chunk_df.to_csv(chunked_pdf_text_file, index=False)

print(f"Chunked text and saved to {chunked_pdf_text_file}")

cl100k_base
Chunked text and saved to data/output/chunked_pdf_text.csv

In [4]:
df= pd.read_csv(chunked_pdf_text_file)
df.head(10)

,chunk_id,start_token,end_token,text
0,20109399_User manual_A1000_en (1).pdf_0000,0,500,USER MANUAL\nA1000\nFCS4050\nen\nRead the user...
1,20109399_User manual_A1000_en (1).pdf_0001,450,950,\n 21\n5.1.2\nOptions\n 22\n5.1.3\nCoffee mach...
2,20109399_User manual_A1000_en (1).pdf_0002,900,1400,10\nEmptying the grounds container\n 41\n7.11\...
3,20109399_User manual_A1000_en (1).pdf_0003,1350,1850,\nMenu 2 Customize beverages\n 64\n10.5.4\nMen...
4,20109399_User manual_A1000_en (1).pdf_0004,1800,2300,3\nShort-term decommissioning (up to 3 weeks)\...
5,20109399_User manual_A1000_en (1).pdf_0005,2250,2750,suitable for the storage of alcoholic or expl...
6,20109399_User manual_A1000_en (1).pdf_0006,2700,3200,for their safety; they are not permitted to pl...
7,20109399_User manual_A1000_en (1).pdf_0007,3150,3650,c) Do not immerse the machine in liquid.\nd) D...
8,20109399_User manual_A1000_en (1).pdf_0008,3600,4100,"at the spouts, thereby\ncontaminating product..."
9,20109399_User manual_A1000_en (1).pdf_0009,4050,4550,\nFranke logo\nCall up the maintenance level\n...

In [5]:
df.shape

(110, 4)

# Step 3: Generate Embeddings

In [6]:
from sentence_transformers import SentenceTransformer

texts = df["text"].tolist()
model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(texts, convert_to_numpy=True, batch_size=32)

embeddings.shape

(110, 384)

In [7]:
import numpy as np

# normalize embeddings
embeddings_normalized = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)

embeddings_normalized.shape

(110, 384)

In [8]:
# Attach to DataFrame

df["embedding"] = [e.tolist() for e in embeddings]
df.to_parquet("data/output/chunked_with_embeddings.parquet", index=False)

df["embedding_normalized"] = [e.tolist() for e in embeddings_normalized]

embeddings_normalized_file = "data/output/chunked_with_embeddings_normalized.parquet"
df.to_parquet(embeddings_normalized_file, index=False)

print(f"Embedded text and saved to {embeddings_normalized_file}")

Embedded text and saved to data/output/chunked_with_embeddings_normalized.parquet

In [9]:
df.head()

,chunk_id,start_token,end_token,text,embedding,embedding_normalized
0,20109399_User manual_A1000_en (1).pdf_0000,0,500,USER MANUAL\nA1000\nFCS4050\nen\nRead the user...,"[-0.035316597670316696, -0.03822093456983566, ...","[-0.035316597670316696, -0.03822093456983566, ..."
1,20109399_User manual_A1000_en (1).pdf_0001,450,950,\n 21\n5.1.2\nOptions\n 22\n5.1.3\nCoffee mach...,"[-0.027215270325541496, -0.0625692754983902, -...","[-0.027215274050831795, -0.0625692829489708, -..."
2,20109399_User manual_A1000_en (1).pdf_0002,900,1400,10\nEmptying the grounds container\n 41\n7.11\...,"[-0.05866292491555214, -0.05717035382986069, -...","[-0.05866292864084244, -0.057170357555150986, ..."
3,20109399_User manual_A1000_en (1).pdf_0003,1350,1850,\nMenu 2 Customize beverages\n 64\n10.5.4\nMen...,"[0.01717332936823368, -0.007878676988184452, -...","[0.01717333123087883, -0.007878677919507027, -..."
4,20109399_User manual_A1000_en (1).pdf_0004,1800,2300,3\nShort-term decommissioning (up to 3 weeks)\...,"[-0.06703410297632217, -0.014838328585028648, ...","[-0.06703411042690277, -0.014838329516351223, ..."

## Step 4: Store in FAISS database

In [10]:
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings

# methods for saving and loading faiss database

# Save a LangChain FAISS vector_store to folder_path
def save_faiss_vector_store(vector_store, folder_path: str):
    vector_store.save_local(folder_path)
    print(f"FAISS vector store saved to '{folder_path}'.")


# Load a LangChain FAISS vector store from folder_path with embedding function using model_name
def load_faiss_vector_store(folder_path: str, model_name: str = "sentence-transformers/all-MiniLM-L6-v2"):
    embedding_function = HuggingFaceEmbeddings(model_name=model_name)
    vector_store = FAISS.load_local(
        folder_path,
        embedding_function,
        allow_dangerous_deserialization=True
    )
    print(f"FAISS vector store loaded from '{folder_path}'.")
    return vector_store

In [11]:
from langchain.schema import Document

docs = [Document(page_content=text) for text in df["text"]]

In [12]:
from langchain.retrievers import BM25Retriever

bm25_retriever = BM25Retriever.from_documents(docs)
bm25_retriever.k = 5  # top 5 documents most similar

In [13]:
import faiss
from langchain_community.vectorstores import FAISS
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_huggingface import HuggingFaceEmbeddings

embedding_function = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# ensure id's are unique
assert df["chunk_id"].is_unique, "chunk_id must be unique"

# dimension of embeddings
embedding_dim = embeddings_normalized.shape[1]

# Create FAISS index (IP for cosine similiarity)
index = faiss.IndexFlatIP(embedding_dim)

# Add embeddings to FAISS index (must be float32)
index.add(embeddings_normalized.astype("float32"))

# Create FAISS vector store in memory (RAM)
vector_store = FAISS(
    embedding_function=embedding_function,
    index=index,
    docstore=InMemoryDocstore({chunk_id: doc for chunk_id, doc in zip(df["chunk_id"], docs)}), # indexes for docs - uses chunk_id
    index_to_docstore_id={i: chunk_id for i, chunk_id in enumerate(df["chunk_id"])} # mapping for embeddings indexes to corresponding docs indexes
)

In [14]:
# save FAISS database

faiss_database = "data/faiss_database"
save_faiss_vector_store(vector_store, faiss_database)

FAISS vector store saved to 'data/faiss_database'.

In [15]:
vector_store = load_faiss_vector_store(faiss_database)

FAISS vector store loaded from 'data/faiss_database'.

In [16]:
# retriever for embeddings from FAISS database
faiss_retriever = vector_store.as_retriever(search_type="mmr", search_kwargs={"k": 5}) # top 5 documents

In [17]:
from langchain.retrievers import EnsembleRetriever

# hyrid retriever combining embeddings and keyword search
ensemble_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, faiss_retriever],
    weights=[0.5, 0.5]  # you can tune these weights
)

**LangGraph + Planner/Synthesizer Set up**

In [23]:
pip install langgraph

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Collecting langgraph
  Downloading langgraph-1.0.1-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: langchain-core>=0.1 in ./.venv/lib/python3.13/site-packages (from langgraph) (0.3.79)
Collecting langgraph-checkpoint<4.0.0,>=2.1.0 (from langgraph)
  Downloading langgraph_checkpoint-3.0.0-py3-none-any.whl.metadata (4.2 kB)
Collecting langgraph-prebuilt<1.1.0,>=1.0.0 (from langgraph)
  Downloading langgraph_prebuilt-1.0.1-py3-none-any.whl.metadata (5.0 kB)
Collecting langgraph-sdk<0.3.0,>=0.2.2 (from langgraph)
  Downloading langgraph_sdk-0.2.9-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: pydantic>=2.7.4 in ./.venv/lib/python3.13/site-packages (from langgraph) (2.11.9)
Requirement already satisfied: xxhash>=3.5.0 in ./.venv/lib/python3.13/site-packages (from langgraph) (3.5.0)
Collecting ormsgpack>=1.10.0 (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph)
  Downloading ormsgpack-1.11.0-cp313-cp313-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl.metadata (1.2 kB)
Requirement already satisfied: httpx>=0.25.2 in ./.venv/lib/python3.13/site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in ./.venv/lib/python3.13/site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph) (3.11.3)
Requirement already satisfied: anyio in ./.venv/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph) (4.11.0)
Requirement already satisfied: certifi in ./.venv/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph) (2025.8.3)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph) (1.0.9)
Requirement already satisfied: idna in ./.venv/lib/python3.13/site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph) (3.10)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.13/site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph) (0.16.0)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in ./.venv/lib/python3.13/site-packages (from langchain-core>=0.1->langgraph) (0.4.30)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in ./.venv/lib/python3.13/site-packages (from langchain-core>=0.1->langgraph) (9.1.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in ./.venv/lib/python3.13/site-packages (from langchain-core>=0.1->langgraph) (1.33)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in ./.venv/lib/python3.13/site-packages (from langchain-core>=0.1->langgraph) (6.0.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in ./.venv/lib/python3.13/site-packages (from langchain-core>=0.1->langgraph) (4.15.0)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in ./.venv/lib/python3.13/site-packages (from langchain-core>=0.1->langgraph) (25.0)
Requirement already satisfied: jsonpointer>=1.9 in ./.venv/lib/python3.13/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core>=0.1->langgraph) (3.0.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in ./.venv/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core>=0.1->langgraph) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in ./.venv/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core>=0.1->langgraph) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in ./.venv/lib/python3.13/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core>=0.1->langgraph) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.13/site-packages (from pydantic>=2.7.4->langgraph) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in ./.venv/lib/python3.13/site-packages (from pydantic>=2.7.4->langgraph) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in ./.venv/lib/python3.13/site-packages (from pydantic>=2.7.4->langgraph) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core>=0.1->langgraph) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.13/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core>=0.1->langgraph) (2.5.0)
Requirement already satisfied: sniffio>=1.1 in ./.venv/lib/python3.13/site-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph) (1.3.1)
Downloading langgraph-1.0.1-py3-none-any.whl (155 kB)
Downloading langgraph_checkpoint-3.0.0-py3-none-any.whl (46 kB)
Downloading langgraph_prebuilt-1.0.1-py3-none-any.whl (28 kB)
Downloading langgraph_sdk-0.2.9-py3-none-any.whl (56 kB)
Downloading ormsgpack-1.11.0-cp313-cp313-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl (368 kB)
Installing collected packages: ormsgpack, langgraph-sdk, langgraph-checkpoint, langgraph-prebuilt, langgraph
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [langgraph]
Successfully installed langgraph-1.0.1 langgraph-checkpoint-3.0.0 langgraph-prebuilt-1.0.1 langgraph-sdk-0.2.9 ormsgpack-1.11.0

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# imports
from langchain_groq import ChatGroq
from langchain.chat_models import init_chat_model
from langchain.tools.retriever import create_retriever_tool
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode, tools_condition
from langchain_core.messages import convert_to_messages
from langgraph.graph import MessagesState
from pydantic import BaseModel, Field
from typing import Literal

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0,
    groq_api_key="GROQ_KEY_HERE"
)

planner_model = llm
grader_model  = llm
synth_model   = llm

# turn your ensemble retriever into a retriever tool
retriever_tool = create_retriever_tool(
    ensemble_retriever,
    name="ensemble_retriever_tool",
    description="Search user manuals and technical documents."
)

**Planner Node**

In [25]:
def generate_query_or_respond(state: MessagesState):
    response = planner_model.bind_tools([retriever_tool]).invoke(state["messages"])
    return {"messages": [response]}

**Grader node**

In [32]:
GRADE_PROMPT = (
    "You are grading whether the retrieved context is relevant to the user's question.\n"
    "Question: {question}\n"
    "Context: {context}\n\n"
    "Is this context relevant? Reply 'yes' or 'no'."
)

class GradeDocuments(BaseModel):
    binary_score: str = Field(description="yes or no")

def grade_documents(state: MessagesState) -> Literal["generate_answer"]:
    question = state["messages"][0].content
    context = state["messages"][-1].content
    prompt = GRADE_PROMPT.format(question=question, context=context)
    response = grader_model.with_structured_output(GradeDocuments).invoke(
        [{"role": "user", "content": prompt}]
    )
    return "generate_answer" if response.binary_score.lower() == "yes" else "no"

**Synthesizer**

In [33]:
SYNTH_PROMPT = (
    "You are an assistant. Use the retrieved context to answer the question.\n"
    "Context:\n{context}\n\nQuestion:\n{question}\n\n"
    "Provide a concise and accurate answer."
)

def generate_answer(state: MessagesState):
    question = state["messages"][0].content
    context = state["messages"][-1].content
    prompt = SYNTH_PROMPT.format(context=context, question=question)
    response = synth_model.invoke([{"role": "user", "content": prompt}])
    return {"messages": [response]}

In [ ]:
# Create a new StateGraph
workflow = StateGraph(MessagesState)

# Add the nodes to the graph
workflow.add_node("generate_query_or_respond", generate_query_or_respond)
workflow.add_node("retrieve", ToolNode([retriever_tool]))
workflow.add_node("synthesizer", generate_answer)
workflow.add_node(generate_answer)

# Define the edges (the flow)
workflow.add_edge(START, "generate_query_or_respond")
workflow.add_conditional_edges("generate_query_or_respond", tools_condition, {"tools": "retrieve", END: END})
workflow.add_conditional_edges("retrieve", grade_documents)
workflow.add_edge("generate_answer", END)

# Compile the graph into a runnable 'app'
app = workflow.compile()

print("LangGraph workflow compiled successfully.")

LangGraph workflow compiled successfully.

**Test**

In [35]:
#testing

query = "How to fill powder in the coffe machine?"

for step in app.stream({"messages": [{"role": "user", "content": query}]}):
    for node_name, update in step.items():
        print(f"--- Update from {node_name} ---")
        print(update["messages"][-1].content)
        print()

--- Update from generate_query_or_respond ---


--- Update from retrieve ---
USER MANUAL
SB1200
FCS4074
en
Read the user manual before working on the machine.
Keep the manual with the machine and pass the manual on to the
next operator if the machine is sold or transferred to a third party.
Franke Kaffeemaschinen AG
Table of contents
User manual SB1200
iii
TABLE OF CONTENTS
1
For your safety
 6
1.1
Intended use
 6
1.2
Prerequisites for using the coffee machine
 7
1.3
Explanation of safety instructions
 7
1.4
Safety concerns when using the coffee machine
 8
2
Explanation of symbols
 11
2.1
Symbols used in the manual
 11
2.2
Symbols used in the software
 11
3
Scope of delivery
 15
4
Identification
 17
4.1
Position of type plates
 17
4.2
Type code
 19
5
Description of machine
 21
5.1
Coffee machine
 21
5.2
Add-on units
 25
5.3
Overview of operating modes
 27
5.4
Franke Digital Services (option)
 29
6
Installation
 30
6.1
Preparations
 30
6.2
Dimensions
 30
6.3
Requirements of the water supply
 33
7
Filling and emptying
 36
7.1
filling the machine
 36
7.2
Filling beans
 36
7.3
Filling powder
 37
7.4
Filling the cooling unit
 37
7.5
Filling the Flavor Station
 40
7.6
Filling the FSU60 CM Flavor Station
 40
7.7
Setting the grind coarseness
 41
7.8
Emptying the bean hopper
 43
7.9
Emptying the powder hopper
 43
7.10
Emptying the grounds container
 44
7.11
Emptying the cooling unit
 45
8
Preparing beverages
 48
8.1
Preparing beverages with Quick Select
 48
8.2
Preparing beverages with ground coffee
 48
8

.
7.2
Filling beans
WARNING
Risk of injury
If objects find their way into the bean hopper or grinder, splinters may be ejected, leading to injury.
a) Never insert any objects into the bean hopper or grinder.
NOTICE
Poor beverage quality
The oil from the coffee beans is deposited on the inside of the bean hopper as a thin film of oil. This de-
posited oil ages quickly and impairs the taste of the beverages produced.
a) Remove the oil film from the inside of the bean hopper on a daily basis.
b) To do this, use a dry cloth or a cloth moistened only with water.
c) Do not use any cleaners, as these alter the taste of the coffee.
Fill the bean hopper with coffee beans.
Fill the powder hopper with powder suitable for automatic coffee makers.
1. Lift off the bean hopper lid.
2. Fill coffee beans.
Franke Kaffeemaschinen AG
Filling and emptying | 7
User manual SB1200
37
3. Fit the lid.
7.3
Filling powder
1. Lift off the powder hopper lid.
2. Fill with powder suitable for automatic bev-
erage dispensers.
3. Fit the lid.
7.4
Filling the cooling unit
CAUTION
Germs in unpasteurized milk
Germs in unpasteurized milk could pose a health hazard.
a) Do not use any unpasteurized milk.
b) Only use pasteurized or long-life milk.
7 | Filling and emptying
Franke Kaffeemaschinen AG
38
User manual SB1200
NOTICE
Machine damage
Using incorrect liquids can damage the machine.
a) Only place milk or ready-to-drink beverages into the Franke container.
b) Use water and a mild cleaner to clean the container.
NOTICE
Spoiled milk and ready-to-drink beverages
Insufficient cooling or hygiene can cause milk and ready-to-drink beverages to spoil.
a) Only use precooled milk and precooled ready-to-drink beverages (2-5 °C).
b) Only clean containers should be filled with milk and ready-to-drink beverages.
c) Only store milk and ready-to-drink beverages in the cooling unit when the cooling unit is in operation.
When the cooling unit is not in operation, e.g. overnight, store

/l)
Electrical conductivity (measured)
50–200 µS/cm (microsiemens)
Iron content
< 0.3 mg/l
– Color: Clear
– Taste: Fresh and pure taste
– Aroma: No perceptible aroma
– No rust particles in the water
– Reverse osmosis: The water must have a dissolved solids content of at least 30-50 ppm (30-50 mg/l)
in order to prevent the boiler being overfilled.
Evaluating the risk of corrosion
The following formula can be used for evaluation:
Calculated conductivity = measured conductivity [μS/cm] – (measured total hardness [dH GH] x constant)
– Measured conductivity in μS/cm
– Measured total hardness in dH GH
– Constant = 30 [μS/cm]/[ dH GH]
Calculated conductivity
Risk of corrosion
<200 μS/cm
low
200 – 500 μS/cm
increased
>500 μS/cm
high
Calculation example:
– Measured conductivity 700 μS/cm
Franke Kaffeemaschinen AG
Installation | 6
User manual SB1200
35
– Measured total hardness 18 dH GH
– Calculated conductivity = 700 μS/cm – (18 x 30 μS/cm) = 160 μS/cm
The result of the calculation is 160 μS/cm and means that there is a low risk of corrosion.
6.3.3
Water outlet
– Drain hose: D = 20 mm, L = 2000 mm
– Connection to a lower-lying siphon
7 | Filling and emptying
Franke Kaffeemaschinen AG
36
User manual SB1200
7
FILLING AND EMPTYING
7.1
filling the machine
NOTICE
Incorrect filling of the hoppers
Incorrectly filling the hoppers can produce defective products and the machine can be damaged as a re-
sult.
a) Fill the bean hopper with coffee beans.
b) Fill the powder hopper with powder suitable for automatic coffee makers.
7.2
Filling beans
WARNING
Risk of injury
If objects find their way into the bean hopper or grinder, splinters may be ejected, leading to injury.
a) Never insert any objects into the bean hopper or

3
Short-term decommissioning (up to 3 weeks)
 84
13.4
Long-term decommissioning
 85
13.5
Transport and storage
 85
13.6
Recommissioning after prolonged periods of storage or non-use
 85
14
Disposal of parts
 86
15
Technical data
 87
15.1
Capacities in accordance with DIN 18873-2:2016-02
 87
15.2
Electrical connection data
 87
Index
 88
Franke Kaffeemaschinen AG
For your safety | 1
User manual A1000
7
1
FOR YOUR SAFETY
1.1
Intended use
1.1.1
Coffee machine
– The A1000 is a commercial machine for preparing beverages and is intended for use in food services,
offices and other similar environments.
– The A1000 is designed to process whole coffee beans, ground coffee, powder that is suitable for auto-
matic devices, and fresh milk.
– The A1000 is intended for the preparation of beverages in accordance with these instructions and the
technical data.
– The A1000 is intended for operation indoors.
Please note
– The A1000 is not suitable for use outdoors.
1.1.2
Add-on units
Cooling unit
– The cooling unit is intended exclusively to keep milk cool for the preparation of coffee drinks with a
Franke coffee machine.
– Only use precooled milk (2-5 °C).
– Remove the milk when the cooling unit is not in use. Store the milk in a suitable refrigerator.
– Use only the recommended cleaners. Other cleaners may leave residues in the milk system.
– The cooling unit is intended exclusively for operation indoors.
– Please also observe the Declaration of Conformity delivered with the device.
Flavor Station
– The Flavor Station is intended exclusively for the automatic conveyance of syrups and other fluid aro-
mas for the preparation of drinks.
Please note
– The Flavor Station is not designed to pump viscous fluids such as chocolate sauce.
– The Flavor Station is not suitable for the storage of alcoholic or explosive substances.
Cup warmer
– The cup warmer is intended only for preheating coffee cups and glasses used when preparing drinks.
Please note
– Drinking containers made of paper or plastic must not be used.

H GH
– Constant = 30 [μS/cm]/[ dH GH]
Calculated conductivity
Risk of corrosion
<200 μS/cm
low
200 – 500 μS/cm
increased
>500 μS/cm
high
Calculation example:
– Measured conductivity 700 μS/cm
– Measured total hardness 18 dH GH
– Calculated conductivity = 700 μS/cm – (18 x 30 μS/cm) = 160 μS/cm
The result of the calculation is 160 μS/cm and means that there is a low risk of corrosion.
6.3.3
Water outlet
– Drain hose: D = 20 mm, L = 2000 mm
– Connection to a lower-lying siphon
Franke Kaffeemaschinen AG
Filling and emptying | 7
User manual A1000
33
7
FILLING AND EMPTYING
7.1
filling the machine
NOTICE
Incorrect filling of the hoppers
Incorrectly filling the hoppers can produce defective products and the machine can be damaged as a re-
sult.
a) Fill the bean hopper with coffee beans.
b) Fill the powder hopper with powder suitable for automatic coffee makers.
7.2
Filling beans
WARNING
Risk of injury
If objects find their way into the bean hopper or grinder, splinters may be ejected, leading to injury.
a) Never insert any objects into the bean hopper or grinder.
NOTICE
Poor beverage quality
The oil from the coffee beans is deposited on the inside of the bean hopper as a thin film of oil. This de-
posited oil ages quickly and impairs the taste of the beverages produced.
a) Remove the oil film from the inside of the bean hopper on a daily basis.
b) To do this, use a dry cloth or a cloth moistened only with water.
c) Do not use any cleaners, as these alter the taste of the coffee.
1. Lift off the bean hopper lid.
2. Fill coffee beans.
7 | Filling and emptying
Franke Kaffeemaschinen AG
34
User manual A1000
3. Fit the lid.
7.3
Filling powder
1. Lift off the powder hopper lid.
2. Fill with powder suitable for automatic bev-
er

chiato
Chocolate
3. Select a product.
ð The preparation begins.
Caffè Crema To Go
Ristretto
Tea water
Chococcino
Espresso
Cappuccino
Double Espresso
Latte macchiato
Chocolate
4. Add more products to the queue list as
needed.
Caffè Crema To Go
Ristretto
Tea water
Chococcino
Espresso
Cappuccino
Double Espresso
Latte macchiato
Chocolate
5. Start the preparation of each of the products
in the queue list by pressing the green but-
ton.
ð The next preparation begins.
ð The product selection appears.
ð
All products are ready.
8.3
Preparing beverages with ground coffee
Only ground coffee may be used. Instant coffee made from dried coffee extract cannot be used.
1. Place an appropriate drinking vessel under
the dispensing spout.
2. Press the Decaffeinated coffee selection but-
ton.
Espresso
Double Espresso
Ristretto
Caffè Crema To Go
ð The Decaffeinated coffee selection button il-
luminates.
Franke Kaffeemaschinen AG
Preparing beverages | 8
User manual A1000
47
3. Open the insertion flap.
4. Fill powder.
5. Close the insertion flap.
6. Confirm the message by pressing OK.
ð The preparation begins.
ð The product selection appears.
ð
The product is ready.
8.4
Preparing hot water
You can stop the hot water spout at any time by pressing the cancel button.
Example: Quick Select
1. Place an appropriate drinking vessel under
the hot water spout.
Espresso
Tea water
Steam
Caffè Crema To Go
2 Espressos
Double Espresso
2. Select Tea water.
Espresso
Double Espresso
Ristretto
Caffè Crema To Go
3. Select the cup size.
ð
Hot water is dispensed until the cycle is
complete.
8 | Preparing beverages
Franke Kaffeemaschinen AG
48
User manual A1000
8.5
Steam dispenser (Autosteam/Autosteam Pro)
Autosteam is suitable for manually heating and foaming/frothing of milk and for heating other drinks.
Using the purging function will remove any condensation from inside

 Kaffeemaschinen AG
34
User manual A1000
3. Fit the lid.
7.3
Filling powder
1. Lift off the powder hopper lid.
2. Fill with powder suitable for automatic bev-
erage dispensers.
3. Fit the lid.
7.4
Filling the cooling unit
CAUTION
Germs in unpasteurized milk
Germs in unpasteurized milk could pose a health hazard.
a) Do not use any unpasteurized milk.
b) Only use pasteurized or long-life milk.
Franke Kaffeemaschinen AG
Filling and emptying | 7
User manual A1000
35
NOTICE
Machine damage
Using incorrect liquids can damage the machine.
a) Only fill the milk container with milk.
b) Use water and a mild cleaner to clean the milk container.
NOTICE
Spoiled milk
Insufficient cooling or hygiene can cause milk to spoil.
a) Only use precooled milk (2-5 °C).
b) Only store milk in the cooling unit during operating hours. Outside operating hours, e.g. overnight, store
the milk in a refrigerator.
c) Clean the machine and cooling unit once a day.
d) Only touch the suction hose, the inside of the milk container, and the milk container lid after sanitizing
your hands, or when wearing single use gloves.
e) Place the container lid with the suction hose on a clean surface only.
The milk system is prepared semi-automatically after a cleaning or a filling procedure. Please observe the
instructions in the event messages. Access to the event messages is through the dashboard.
7.4.1
Cooling unit SU12/UT12
NOTICE! This cooling unit is available in several versions and may therefore differ from the following
illustrations depending on the configuration.
1. Open the door.
2. Switch the cooling unit on.
ð The current cooling chamber temperature
is displayed.
3. Only pull out the milk container until the point
where the sliding cover of the container lid is
fully visible.
7 | Filling and emptying
Franke Kaffeemaschinen AG
36
User manual A1000
4. Push the sliding cover backwards.
5. Fill the milk container with cooled milk.
6. Close the sliding cover.
7. Push the milk container all the way into the
cooling


Description
Clean components using the 5-step method.
This symbol indicates tips, tricks and additional information
Prerequisites for additional steps
Result or intermediate result for additional steps
2.2
Symbols used in the software
2.2.1
Symbols used for navigation and operation
Symbol
Designation
Description
Cancel button
Cancel preparation
Select next/previous
page
Scroll through menus with multiple pages
Start button
Start preparation
2.2.2
Symbols on the dashboard and on the user interface
When a symbol is illuminated on the dashboard, additional information and instructions can be displayed
by tapping the symbol. If an error occurs, refer to the Troubleshooting [} 79] chapter for help.
Symbol
Designation
Description
Franke logo
Call up the maintenance level
Bean left/right
Active grinder
2 | Explanation of symbols
Franke Kaffeemaschinen AG
12
User manual SB1200
Symbol
Designation
Description
Double product
Produce double beverage quantity (double production)
Ground coffee
Energy-saving mode
Switch the machine into energy-saving mode
Servicing/cleaning
Machine must be cleaned and/or serviced
Rinse
Machine must be rinsed or machine is rinsing
Milk system cleaning
agent
Milk system cleaning agent is empty (CleanMaster)
Grounds container
Grounds container must be emptied
Door
The door is open
First Shot
Preheat system
Service/configuration/
administration
Brightness
Set brightness
Individualization
Customize beverages and display
Screen saver
Advertising images
Favorites
Favorites button, can be assigned to a function that is used fre-
quently
Product
Coffee bean
Bean hopper is empty or not installed correctly
Franke Kaffeemaschinen AG
Explanation of symbols | 2
User manual SB1200
13
Symbol
Designation
Description
Milk
Milk container is empty or not installed correctly
Powder resource
Powder hopper is empty or not installed correctly
Info
Event log
List of event and error messages
Individual products
counter
Inactive
Data transfer
Data is being transferred
2.2.3
Depiction of error messages
Espresso
Cappuccino
Chococcino
Caffè Crema To Go
Steam
Tea water
Highlighted products cannot be prepared. The illu-
minated symbol on the

 for the coffee machine must be protected by a residual current circuit-
breaker (RCCB).
– Each terminal of the power supply must be able to be interrupted using a switch.
– The water connection must comply with Requirements of the water supply [} 33] and local and
national rules and regulations.
– The coffee machine must be connected to the water supply with the supplied hose kit. Do not use any
other water hoses that happen to be present.
– Make sure to provide a stable, ergonomic cup tray (min. load capacity 150 kg). The operator panel
should be at eye level.
You must have completed these preparations before one of our service technicians can install the coffee
machine for you. Your service technician will install your coffee machine and carry out the initial commis-
sioning process. He will instruct you in the basic functions.
6.2
Dimensions
All dimensions are specified in mm.
More comprehensive specifications are required for setting up the counter furniture. Consult the design
data with regard to this.
NOTICE
Overheating damage
If the clearances around and above the machine are too small, heat may accumulate in the machine and
lead to faults.
a) Maintain the prescribed installation dimensions and clearances.
b) Take care to ensure that the clearance spaces are not blocked.
Franke Kaffeemaschinen AG
Installation | 6
User manual SB1200
31
SB1200 FM CM - front/side view
UT40 cooling unit, FSU60 CM and CleanMaster module in furniture - front/side view
6 | Installation
Franke Kaffeemaschinen AG
32
User manual SB1200
SB1200 FM CM with SU12 cooling unit and FS60 CM - front/side view
SB1200 FM CM with UT12 cooling unit - front/side view
Minimum clearances
– To the rear panel: 50 mm
– Above: 200 mm (for filling and removal of the bean hopper)
– To the right: 100 mm (for opening the door)
Openings in counter top
The following illustrations are examples. Please refer to the design data for the details that match your
configuration.
Franke Kaffeemaschinen AG
Installation | 6
User manual SB1200
33
Openings in counter top when using adjustable feet
Opening in counter top when using the molded gasket
6.2.1


] and local and
national rules and regulations.
– The coffee machine must be connected to the water supply with the supplied hose kit. Do not use any
other water hoses that happen to be present.
– Ensure that the coffee machine can be placed on a horizontal and stable support with a load capacity
of min. 150 kg. The operator panel should be at eye level and allow ergonomic operation.
You must have completed these preparations before a service technician can install the coffee machine
for you. The service technician will install your coffee machine and carry out the initial commissioning
process. The technician will walk you through the basic functions.
6.2
Dimensions
All dimensions are specified in mm.
Front/side view
6 | Installation
Franke Kaffeemaschinen AG
30
User manual A1000
Minimum distances, top and rear
Only for the
coffee grounds
ejection option
Hose feedthrough in the counter
Minimum clearances
– To the rear panel: 50 mm
– Above: 200 mm (for filling and removal of the bean hopper)
– To the right: 100 mm (for opening the door)
Franke Kaffeemaschinen AG
Installation | 6
User manual A1000
31
NOTICE
Overheating damage
If the clearances around and above the machine are too small, heat may accumulate in the machine and
lead to faults.
a) Maintain the prescribed installation dimensions and clearances.
b) Take care to ensure that the clearance spaces are not blocked.
6.2.1
Feet
A1000 is delivered with feet.
– Feet 40 mm (standard)
– Feet 7 mm (option)
– Feet 70 mm (option)
– Feet 100 mm (option)
Adjustable feet can be used to compensate for unevenness or differences in height.
6.3
Requirements of the water supply
6.3.1
Main water connection
Water pressure
0,8-8,0 bar
Flow rate
>100 ml/s
Water temperature
<25 °C
Connection to the main water connection
G3/8" compression fitting and metal hose l = 1500
mm
Only connect with the hose kit provided
– The main water connection must meet the requirements of the technical data and comply with appli-
cable federal, state, and local regulations.
– The main water connection

--- Update from generate_answer ---
To fill powder in the coffee machine, follow these steps:
1. Lift off the powder hopper lid.
2. Fill with powder suitable for automatic beverage dispensers.
3. Fit the lid.

In [18]:
#simple semantic search example 1 using ensemble 

query = "How to fill powder in the coffee machine"
ensemble_results = ensemble_retriever.get_relevant_documents(query)

for i, doc in enumerate(ensemble_results, 1):
    print(f"\nEnsemble Result {i}")
    print(doc.page_content[:500])

Ensemble Result 1
bleshooting | 12
User manual SB1200
81
The aromas of the coffee beans evaporate in the bean hopper as a result of heat and air exchange. The
quality will have already deteriorated after 3 hours.
a) Coffee beans should not be moist.
b) Seal any open coffee bean packs in an airtight manner.
c) Do not store coffee beans in a refrigerator or freezer.
d) Only fill the coffee beans into the bean hopper that you will need for the next 3 hours.
12.4
Help with problems concerning product quality
Problem


Ensemble Result 2
.
7.2
Filling beans
WARNING
Risk of injury
If objects find their way into the bean hopper or grinder, splinters may be ejected, leading to injury.
a) Never insert any objects into the bean hopper or grinder.
NOTICE
Poor beverage quality
The oil from the coffee beans is deposited on the inside of the bean hopper as a thin film of oil. This de-
posited oil ages quickly and impairs the taste of the beverages produced.
a) Remove the oil film from the inside of the bean hopper on a daily basis.
b) To

Ensemble Result 3
 water tank/main water con-
nection coupling
If the error message appears while a
product is being dispensed, the brewing
module strainer is probably blocked
– Increase the grind coarseness and/or
reduce the grind quantity
– Remove the brewing module and
rinse it out
– Start the coffee machine cleaning
process
12 | Troubleshooting
Franke Kaffeemaschinen AG
82
User manual A1000
Error message/problem Possible cause
Measure
Touch screen not re-
sponding correctly
Overloaded machine software
There a

Ensemble Result 4
 (12 l or 2 x 4.5 l)
MU
Milk pump module
FS60
Flavor Station with 6 flavor pumps
FSU60
Under-counter Flavor Station with 6 flavor pumps
CW
Cup warmer
FM
FoamMaster (cold and warm milk, cold and warm milk foam)
CM
CleanMaster
Twin
Modified cooling unit for the simultaneous use with two coffee machines
AC
Accounting system
CC
Coin changer
CL
Cashless
CV
Coin validator
Franke Kaffeemaschinen AG
Description of machine | 5
User manual A1000
21
5
DESCRIPTION OF MACHINE
5.1
Coffee machine
The A1000 cof

Ensemble Result 5
 Kaffeemaschinen AG
34
User manual A1000
3. Fit the lid.
7.3
Filling powder
1. Lift off the powder hopper lid.
2. Fill with powder suitable for automatic bev-
erage dispensers.
3. Fit the lid.
7.4
Filling the cooling unit
CAUTION
Germs in unpasteurized milk
Germs in unpasteurized milk could pose a health hazard.
a) Do not use any unpasteurized milk.
b) Only use pasteurized or long-life milk.
Franke Kaffeemaschinen AG
Filling and emptying | 7
User manual A1000
35
NOTICE
Machine damage
Using incor

Ensemble Result 6
chiato
Chocolate
3. Select a product.
ð The preparation begins.
Caffè Crema To Go
Ristretto
Tea water
Chococcino
Espresso
Cappuccino
Double Espresso
Latte macchiato
Chocolate
4. Add more products to the queue list as
needed.
Caffè Crema To Go
Ristretto
Tea water
Chococcino
Espresso
Cappuccino
Double Espresso
Latte macchiato
Chocolate
5. Start the preparation of each of the products
in the queue list by pressing the green but-
ton.
ð The next preparation begins.
ð The product selection appears.
ð

Ensemble Result 7
 leading to injury.
a) Never insert any objects into the bean hopper or grinder.
CAUTION
Cutting injuries/crushing
The powder hoppers worm gear mechanism can cause cuts or crushing injuries.
a) Exercise care when cleaning the powder hopper.
1 | For your safety
Franke Kaffeemaschinen AG
10
User manual SB1200
CAUTION
Irritation from cleaners
Cleaning tablets, milk system cleaning agent, and descaler can lead to irritation of the skin or eyes.
a) Observe the hazard warnings on the label of the resp

Ensemble Result 8
 on or off.
9.2
Required cleaning accessories
– Cleaning tablets
– Microfiber cloth
– Paint brush
– Brush set
– Spout cleaning device (if the hot water also comes from the central spout)
– Paper towel (for all-in-one spout)
9.3
5-step method
Clean the removable components of your coffee machine using the 5-step method. The display shows
you the components that can be removed during cleaning.
Clean the container and accessories of the cooling unit
Clean the containers and accessories, such as the

Ensemble Result 9
 using the automatic
Cleaning [} 49] function.
2. Empty the bean hopper and powder hopper.
3. Clean the bean hopper and powder hopper.
4. Clean the grounds container.
5. Empty the milk container.
6. Clean the milk container and container lid.
7. Clean the inside of the milk hose with a
brush.
8. Clean the suction filter with a twisted-in-wire
brush.
9. Clean the reversible adapter.
13.2
Back up data
Back up the data if the machine is to be recommissioned later or if the machine is to be replaced

Ensemble Result 10
 be impaired.
a) Push the locking slide all the way in.
7.9
Emptying the powder hopper
CAUTION
Cutting injuries/crushing
The powder hoppers worm gear mechanism can cause cuts or crushing injuries.
a) Exercise care when cleaning the powder hopper.
NOTICE
Contamination from powder
Powder can fall from the powder hopper.
a) Always transport the powder hopper in an upright position and ensure it is closed.
Franke Kaffeemaschinen AG
Filling and emptying | 7
User manual A1000
41
1. Pull the locking sl

/var/folders/00/y3h49vl51pzcq863ng7prm200000gn/T/ipykernel_8081/1226455666.py:4: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  ensemble_results = ensemble_retriever.get_relevant_documents(query)

# Evaluation for Milestone 1

In [19]:
#without LLM
from ragas import SingleTurnSample
from ragas.metrics import NonLLMContextPrecisionWithReference

context_precision = NonLLMContextPrecisionWithReference()

retrieved_contexts = [doc.page_content for doc in results]

reference_text = """
1. Lift off the powder hopper lid.
2. Fill with powder suitable for automatic beverage dispensers.
3. Fit the lid.
"""

sample = SingleTurnSample(
    retrieved_contexts=retrieved_contexts,
    reference_contexts=[reference_text]
)

score = await context_precision.single_turn_ascore(sample)
print("Non-LLM context precision score:", score)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

NameError: name 'results' is not defined

In [ ]:
#with LLM using Groq
from ragas import SingleTurnSample
from ragas.metrics import ContextPrecision
from ragas.llms import LangchainLLMWrapper
from langchain_groq import ChatGroq


langchain_llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0,
    groq_api_key="" #api key
)
ragas_llm = LangchainLLMWrapper(langchain_llm)

context_precision = ContextPrecision(llm=ragas_llm)

retrieved_contexts = [doc.page_content for doc in results]

reference_text = """
1. Lift off the powder hopper lid.
2. Fill with powder suitable for automatic beverage dispensers.
3. Fit the lid.
"""

sample = SingleTurnSample(
    user_input=query,
    reference=reference_text,
    retrieved_contexts=retrieved_contexts
)

score = await context_precision.single_turn_ascore(sample)
print("LLM-based context precision score:", score)

LLM-based context precision score: 0.1249999999875

In [ ]:
context_precision = ContextPrecision(llm=ragas_llm)

query = "Error Message: No milk or just milk foam"
results = ensemble_retriever.get_relevant_documents(query)
retrieved_contexts = [doc.page_content for doc in results]

reference_text = """
Possible cause: Suction hose/milk line has a leak
Measure: Check the position of the spout insert and, if necessary, clean it. SU05 cooling
unit: Check the O-ring on the suction hose coupling. Check the suction hose and, if necessary, replace it
"""

sample = SingleTurnSample(
    user_input=query,
    reference=reference_text,
    retrieved_contexts=retrieved_contexts
)

score = await context_precision.single_turn_ascore(sample)
print("LLM-based context precision score:", score)

LLM-based context precision score: 0.8055555555287036

**