<a href="https://colab.research.google.com/github/w-lly/Agentic-AI-for-Insights/blob/Task-1-pdf-scanning/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install requirements

In [ ]:
%pip install pymupdf
%pip install pandas
%pip install tiktoken
%pip install sentence-transformers
%pip install pyarrow # for Parquet support
%pip install numpy
%pip install langchain
%pip install langchain-community
%pip install -U langchain-huggingface # for depreciation warning
%pip install rank_bm25
%pip install faiss-cpu

# Step 1: Extract text from the PDF using PyMuPDF

In [1]:
import fitz
import pymupdf
import pandas as pd
import os

input_folder = "data/input/"
files = [f for f in os.listdir(input_folder) if f.endswith(".pdf")]
df = pd.DataFrame(columns=["file_name", "text"])

for file in files:
    path = os.path.join(input_folder, file)
    doc = pymupdf.open(path)
    print(f"Processing {file} with {doc.page_count} pages...")
    extracted_text = ""
    for page in doc:
        extracted_text += page.get_text()
    df.loc[df.shape[0]] = {"file_name": file, "text": extracted_text}

# Save to CSV
extracted_text_file = "extracted_text_from_pdfs.csv"
df.to_csv(f"data/output/{extracted_text_file}", index=False)

print(f"Extracted text and saved to {extracted_text_file}")

Processing 20109399_User manual_A1000_en (1).pdf with 92 pages...
Processing 20169320_TUM_SB1200_en.pdf with 88 pages...
Extracted text and saved to extracted_text_from_pdfs.csv

# Step 2: Chunk text with metadata

In [2]:
import tiktoken
import pandas as pd

# Load tokenizer
encoding = tiktoken.encoding_for_model("gpt-3.5-turbo")
print(encoding.name)

# Chunking function
def chunk_text_with_metadata(text, chunk_size=500, overlap=50):
    tokens = encoding.encode(text)
    chunks = []
    start = 0
    chunk_id = 0

    while start < len(tokens):
        end = start + chunk_size
        chunk_tokens = tokens[start:end]
        chunk_text = encoding.decode(chunk_tokens)

        chunks.append({
            "chunk_id": chunk_id,
            "start_token": start,
            "end_token": end,
            "text": chunk_text
        })

        chunk_id += 1
        start += chunk_size - overlap  # sliding window
    return pd.DataFrame(chunks)

def chunk_multi_text_with_metadata(filenames, texts, chunk_size=500, overlap=50):
    assert len(filenames) == len(texts), "length of filenames must match length of texts"
    chunk_df_lst = []
    for i in range(len(texts)):
        chunk_df = chunk_text_with_metadata(texts[i], chunk_size, overlap)
        chunk_df["chunk_id"] = chunk_df["chunk_id"].apply(lambda x: f"{filenames[i]}_{x:04d}")
        chunk_df_lst.append(chunk_df)
    return pd.concat(chunk_df_lst, ignore_index=True)

chunk_df = chunk_multi_text_with_metadata(df["file_name"], df["text"])

chunked_pdf_text_file = "data/output/chunked_pdf_text.csv"
chunk_df.to_csv(chunked_pdf_text_file, index=False)

print(f"Chunked text and saved to {chunked_pdf_text_file}")

cl100k_base
Chunked text and saved to data/output/chunked_pdf_text.csv

In [3]:
df= pd.read_csv(chunked_pdf_text_file)
df.head(10)

,chunk_id,start_token,end_token,text
0,20109399_User manual_A1000_en (1).pdf_0000,0,500,USER MANUAL\nA1000\nFCS4050\nen\nRead the user...
1,20109399_User manual_A1000_en (1).pdf_0001,450,950,\n 21\n5.1.2\nOptions\n 22\n5.1.3\nCoffee mach...
2,20109399_User manual_A1000_en (1).pdf_0002,900,1400,10\nEmptying the grounds container\n 41\n7.11\...
3,20109399_User manual_A1000_en (1).pdf_0003,1350,1850,\nMenu 2 Customize beverages\n 64\n10.5.4\nMen...
4,20109399_User manual_A1000_en (1).pdf_0004,1800,2300,3\nShort-term decommissioning (up to 3 weeks)\...
5,20109399_User manual_A1000_en (1).pdf_0005,2250,2750,suitable for the storage of alcoholic or expl...
6,20109399_User manual_A1000_en (1).pdf_0006,2700,3200,for their safety; they are not permitted to pl...
7,20109399_User manual_A1000_en (1).pdf_0007,3150,3650,c) Do not immerse the machine in liquid.\nd) D...
8,20109399_User manual_A1000_en (1).pdf_0008,3600,4100,"at the spouts, thereby\ncontaminating product..."
9,20109399_User manual_A1000_en (1).pdf_0009,4050,4550,\nFranke logo\nCall up the maintenance level\n...

In [4]:
df.shape

(110, 4)

# Step 3: Generate Embeddings

In [5]:
from sentence_transformers import SentenceTransformer

texts = df["text"].tolist()
model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(texts, convert_to_numpy=True, batch_size=32)

embeddings.shape

(110, 384)

In [6]:
import numpy as np

# normalize embeddings
embeddings_normalized = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)

embeddings_normalized.shape

(110, 384)

In [7]:
# Attach to DataFrame

df["embedding"] = [e.tolist() for e in embeddings]
df.to_parquet("data/output/chunked_with_embeddings.parquet", index=False)

df["embedding_normalized"] = [e.tolist() for e in embeddings_normalized]

embeddings_normalized_file = "data/output/chunked_with_embeddings_normalized.parquet"
df.to_parquet(embeddings_normalized_file, index=False)

print(f"Embedded text and saved to {embeddings_normalized_file}")

Embedded text and saved to data/output/chunked_with_embeddings_normalized.parquet

In [8]:
df.head()

,chunk_id,start_token,end_token,text,embedding,embedding_normalized
0,20109399_User manual_A1000_en (1).pdf_0000,0,500,USER MANUAL\nA1000\nFCS4050\nen\nRead the user...,"[-0.03531654551625252, -0.03822091966867447, -...","[-0.03531654551625252, -0.03822091966867447, -..."
1,20109399_User manual_A1000_en (1).pdf_0001,450,950,\n 21\n5.1.2\nOptions\n 22\n5.1.3\nCoffee mach...,"[-0.027215251699090004, -0.06256923824548721, ...","[-0.027215251699090004, -0.06256923824548721, ..."
2,20109399_User manual_A1000_en (1).pdf_0002,900,1400,10\nEmptying the grounds container\n 41\n7.11\...,"[-0.058662887662649155, -0.057170357555150986,...","[-0.05866289138793945, -0.057170361280441284, ..."
3,20109399_User manual_A1000_en (1).pdf_0003,1350,1850,\nMenu 2 Customize beverages\n 64\n10.5.4\nMen...,"[0.017173321917653084, -0.007878727279603481, ...","[0.017173323780298233, -0.007878728210926056, ..."
4,20109399_User manual_A1000_en (1).pdf_0004,1800,2300,3\nShort-term decommissioning (up to 3 weeks)\...,"[-0.06703411787748337, -0.014838384464383125, ...","[-0.06703411787748337, -0.014838384464383125, ..."

## Store in FAISS database

In [9]:
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings

# methods for saving and loading faiss database

# Save a LangChain FAISS vector_store to folder_path
def save_faiss_vector_store(vector_store, folder_path: str):
    vector_store.save_local(folder_path)
    print(f"FAISS vector store saved to '{folder_path}'.")


# Load a LangChain FAISS vector store from folder_path with embedding function using model_name
def load_faiss_vector_store(folder_path: str, model_name: str = "sentence-transformers/all-MiniLM-L6-v2"):
    embedding_function = HuggingFaceEmbeddings(model_name=model_name)
    vector_store = FAISS.load_local(
        folder_path,
        embedding_function,
        allow_dangerous_deserialization=True
    )
    print(f"FAISS vector store loaded from '{folder_path}'.")
    return vector_store

In [10]:
from langchain.schema import Document

docs = [Document(page_content=text) for text in df["text"]]

In [11]:
from langchain.retrievers import BM25Retriever

bm25_retriever = BM25Retriever.from_documents(docs)
bm25_retriever.k = 5  # top 5 documents most similar

In [12]:
import faiss
from langchain_community.vectorstores import FAISS
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_huggingface import HuggingFaceEmbeddings

embedding_function = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# ensure id's are unique
assert df["chunk_id"].is_unique, "chunk_id must be unique"

# dimension of embeddings
embedding_dim = embeddings_normalized.shape[1]

# Create FAISS index (IP for cosine similiarity)
index = faiss.IndexFlatIP(embedding_dim)

# Add embeddings to FAISS index (must be float32)
index.add(embeddings_normalized.astype("float32"))

# Create FAISS vector store in memory (RAM)
vector_store = FAISS(
    embedding_function=embedding_function,
    index=index,
    docstore=InMemoryDocstore({chunk_id: doc for chunk_id, doc in zip(df["chunk_id"], docs)}), # indexes for docs - uses chunk_id
    index_to_docstore_id={i: chunk_id for i, chunk_id in enumerate(df["chunk_id"])} # mapping for embeddings indexes to corresponding docs indexes
)

In [13]:
# save FAISS database

faiss_database = "data/faiss_database"
save_faiss_vector_store(vector_store, faiss_database)

FAISS vector store saved to 'data/faiss_database'.

In [14]:
vector_store = load_faiss_vector_store(faiss_database)

FAISS vector store loaded from 'data/faiss_database'.

In [15]:
# retriever for embeddings from FAISS database
faiss_retriever = vector_store.as_retriever(search_type="mmr", search_kwargs={"k": 5}) # top 5 documents

In [16]:
from langchain.retrievers import EnsembleRetriever

# hyrid retriever combining embeddings and keyword search
ensemble_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, faiss_retriever],
    weights=[0.5, 0.5]  # you can tune these weights
)