<a href="https://colab.research.google.com/github/w-lly/Agentic-AI-for-Insights/blob/Task-4-FAISS-Database/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install requirements

In [2]:
%pip install pymupdf
%pip install pandas
%pip install tiktoken
%pip install sentence-transformers
%pip install pyarrow # for Parquet support
%pip install numpy
%pip install langchain
%pip install langchain-community
%pip install -U langchain-huggingface # for depreciation warning
%pip install rank_bm25
%pip install faiss-cpu
%pip install ragas
%pip install rapidfuzz
%pip install langchain_groq
%pip install openai

Collecting pymupdf
  Downloading pymupdf-1.26.4-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Downloading pymupdf-1.26.4-cp39-abi3-manylinux_2_28_x86_64.whl (24.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 88.2 MB/s eta 0:00:00
Installing collected packages: pymupdf
Successfully installed pymupdf-1.26.4
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (0.11.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2024.11.6)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken) (2025.8.3)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.1.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.56.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.8.0+cu126)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.2)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.35.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.10)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.22.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.6.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.8.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (0.3.27)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.72 in /usr/local/lib/python3.12/dist-packages (from langchain) (0.3.76)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in /usr/local/lib/python3.12/dist-packages (from langchain) (0.3.11)
Requirement already satisfied: langsmith>=0.1.17 in /usr/local/lib/python3.12/dist-packages (from langchain) (0.4.28)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.11.9)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.0.43)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.32.4)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.12/dist-packages (from langchain) (6.0.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (8.5.0)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.12/dist-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (1.33)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.12/dist-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (4.15.0)
Requirement already satisfied: packaging>=23.2 in /usr/local/lib/python3.12/dist-packages (from langchain-core<1.0.0,>=0.3.72->langchain) (25.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.17->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.17->langchain) (3.11.3)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith>=0.1.17->langchain) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2->langchain) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2->langchain) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2->langchain) (2025.8.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3,>=1.4->langchain) (3.2.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (4.10.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.72->langchain) (3.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.1.17->langchain) (1.3.1)
Collecting langchain-community
  Downloading langchain_community-0.3.30-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: langchain-core<2.0.0,>=0.3.75 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.3.76)
Requirement already satisfied: langchain<2.0.0,>=0.3.27 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.3.27)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.43)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.12.15)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (8.5.0)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.10.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.28)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.1)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.20.1)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.9 in /usr/local/lib/python3.12/dist-packages (from langchain<2.0.0,>=0.3.27->langchain-community) (0.3.11)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain<2.0.0,>=0.3.27->langchain-community) (2.11.9)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=0.3.75->langchain-community) (1.33)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=0.3.75->langchain-community) (4.15.0)
Requirement already satisfied: packaging>=23.2 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=0.3.75->langchain-community) (25.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.3)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.1.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2025.8.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.2.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.10.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<2.0.0,>=0.3.75->langchain-community) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain<2.0.0,>=0.3.27->langchain-community) (2.33.2)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.3.1)
Downloading langchain_community-0.3.30-py3-none-any.whl (2.5 MB)

# Step 1: Extract text from the PDF using PyMuPDF

In [3]:
import fitz
import pymupdf
import pandas as pd
import os

input_folder = "data/input/"
files = [f for f in os.listdir(input_folder) if f.endswith(".pdf")]
df = pd.DataFrame(columns=["file_name", "text"])

for file in files:
    path = os.path.join(input_folder, file)
    doc = pymupdf.open(path)
    print(f"Processing {file} with {doc.page_count} pages...")
    extracted_text = ""
    for page in doc:
        extracted_text += page.get_text()
    df.loc[df.shape[0]] = {"file_name": file, "text": extracted_text}

# Save to CSV
extracted_text_file = "extracted_text_from_pdfs.csv"
df.to_csv(f"data/output/{extracted_text_file}", index=False)

print(f"Extracted text and saved to {extracted_text_file}")

Processing 20169320_TUM_SB1200_en.pdf with 88 pages...
Processing 20109399_User manual_A1000_en (1).pdf with 92 pages...
Extracted text and saved to extracted_text_from_pdfs.csv

# Step 2: Chunk text with metadata

In [4]:
import tiktoken
import pandas as pd

# Load tokenizer
encoding = tiktoken.encoding_for_model("gpt-3.5-turbo")
print(encoding.name)

# Chunking function
def chunk_text_with_metadata(text, chunk_size=500, overlap=50):
    tokens = encoding.encode(text)
    chunks = []
    start = 0
    chunk_id = 0

    while start < len(tokens):
        end = start + chunk_size
        chunk_tokens = tokens[start:end]
        chunk_text = encoding.decode(chunk_tokens)

        chunks.append({
            "chunk_id": chunk_id,
            "start_token": start,
            "end_token": end,
            "text": chunk_text
        })

        chunk_id += 1
        start += chunk_size - overlap  # sliding window
    return pd.DataFrame(chunks)

def chunk_multi_text_with_metadata(filenames, texts, chunk_size=500, overlap=50):
    assert len(filenames) == len(texts), "length of filenames must match length of texts"
    chunk_df_lst = []
    for i in range(len(texts)):
        chunk_df = chunk_text_with_metadata(texts[i], chunk_size, overlap)
        chunk_df["chunk_id"] = chunk_df["chunk_id"].apply(lambda x: f"{filenames[i]}_{x:04d}")
        chunk_df_lst.append(chunk_df)
    return pd.concat(chunk_df_lst, ignore_index=True)

chunk_df = chunk_multi_text_with_metadata(df["file_name"], df["text"])

chunked_pdf_text_file = "data/output/chunked_pdf_text.csv"
chunk_df.to_csv(chunked_pdf_text_file, index=False)

print(f"Chunked text and saved to {chunked_pdf_text_file}")

cl100k_base
Chunked text and saved to data/output/chunked_pdf_text.csv

In [5]:
df= pd.read_csv(chunked_pdf_text_file)
df.head(10)

,chunk_id,start_token,end_token,text
0,20169320_TUM_SB1200_en.pdf_0000,0,500,USER MANUAL\nSB1200\nFCS4074\nen\nRead the use...
1,20169320_TUM_SB1200_en.pdf_0001,450,950,44\n7.11\nEmptying the cooling unit\n 45\n8\nP...
2,20169320_TUM_SB1200_en.pdf_0002,900,1400,.4\nLong-term decommissioning\n 82\n13.5\nTran...
3,20169320_TUM_SB1200_en.pdf_0003,1350,1850,intended exclusively for operation indoors.\n...
4,20169320_TUM_SB1200_en.pdf_0004,1800,2300,or add-on units if you are not familiar with ...
5,20169320_TUM_SB1200_en.pdf_0005,2250,2750,"is permanently assembled, contact the service..."
6,20169320_TUM_SB1200_en.pdf_0006,2700,3200,leading to injury.\na) Never insert any objec...
7,20169320_TUM_SB1200_en.pdf_0007,3150,3650,\nDescription\nClean components using the 5-st...
8,20169320_TUM_SB1200_en.pdf_0008,3600,4100,.3\nDepiction of error messages\nEspresso\nCap...
9,20169320_TUM_SB1200_en.pdf_0009,4050,4550,for fixing are included)\n560.0623.576\nFrank...

In [6]:
df.shape

(110, 4)

# Step 3: Generate Embeddings

In [7]:
from sentence_transformers import SentenceTransformer

texts = df["text"].tolist()
model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(texts, convert_to_numpy=True, batch_size=32)

embeddings.shape

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

(110, 384)

In [8]:
import numpy as np

# normalize embeddings
embeddings_normalized = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)

embeddings_normalized.shape

(110, 384)

In [9]:
# Attach to DataFrame

df["embedding"] = [e.tolist() for e in embeddings]
df.to_parquet("data/output/chunked_with_embeddings.parquet", index=False)

df["embedding_normalized"] = [e.tolist() for e in embeddings_normalized]

embeddings_normalized_file = "data/output/chunked_with_embeddings_normalized.parquet"
df.to_parquet(embeddings_normalized_file, index=False)

print(f"Embedded text and saved to {embeddings_normalized_file}")

Embedded text and saved to data/output/chunked_with_embeddings_normalized.parquet

In [10]:
df.head()

,chunk_id,start_token,end_token,text,embedding,embedding_normalized
0,20169320_TUM_SB1200_en.pdf_0000,0,500,USER MANUAL\nSB1200\nFCS4074\nen\nRead the use...,"[-0.04090375825762749, -0.06303814053535461, -...","[-0.040903761982917786, -0.06303814798593521, ..."
1,20169320_TUM_SB1200_en.pdf_0001,450,950,44\n7.11\nEmptying the cooling unit\n 45\n8\nP...,"[0.0004648288304451853, -0.10623930394649506, ...","[0.0004648288304451853, -0.10623930394649506, ..."
2,20169320_TUM_SB1200_en.pdf_0002,900,1400,.4\nLong-term decommissioning\n 82\n13.5\nTran...,"[-0.023924756795167923, -0.04593826085329056, ...","[-0.023924758657813072, -0.045938264578580856,..."
3,20169320_TUM_SB1200_en.pdf_0003,1350,1850,intended exclusively for operation indoors.\n...,"[-0.02526177652180195, -0.07155144214630127, -...","[-0.025261778384447098, -0.07155144959688187, ..."
4,20169320_TUM_SB1200_en.pdf_0004,1800,2300,or add-on units if you are not familiar with ...,"[-0.01279999129474163, -0.034887202084064484, ...","[-0.01279999129474163, -0.034887202084064484, ..."

## Store in FAISS database

In [11]:
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings

# methods for saving and loading faiss database

# Save a LangChain FAISS vector_store to folder_path
def save_faiss_vector_store(vector_store, folder_path: str):
    vector_store.save_local(folder_path)
    print(f"FAISS vector store saved to '{folder_path}'.")


# Load a LangChain FAISS vector store from folder_path with embedding function using model_name
def load_faiss_vector_store(folder_path: str, model_name: str = "sentence-transformers/all-MiniLM-L6-v2"):
    embedding_function = HuggingFaceEmbeddings(model_name=model_name)
    vector_store = FAISS.load_local(
        folder_path,
        embedding_function,
        allow_dangerous_deserialization=True
    )
    print(f"FAISS vector store loaded from '{folder_path}'.")
    return vector_store

In [12]:
from langchain.schema import Document

docs = [Document(page_content=text) for text in df["text"]]

In [13]:
from langchain.retrievers import BM25Retriever

bm25_retriever = BM25Retriever.from_documents(docs)
bm25_retriever.k = 5  # top 5 documents most similar

In [14]:
import faiss
from langchain_community.vectorstores import FAISS
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_huggingface import HuggingFaceEmbeddings

embedding_function = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# ensure id's are unique
assert df["chunk_id"].is_unique, "chunk_id must be unique"

# dimension of embeddings
embedding_dim = embeddings_normalized.shape[1]

# Create FAISS index (IP for cosine similiarity)
index = faiss.IndexFlatIP(embedding_dim)

# Add embeddings to FAISS index (must be float32)
index.add(embeddings_normalized.astype("float32"))

# Create FAISS vector store in memory (RAM)
vector_store = FAISS(
    embedding_function=embedding_function,
    index=index,
    docstore=InMemoryDocstore({chunk_id: doc for chunk_id, doc in zip(df["chunk_id"], docs)}), # indexes for docs - uses chunk_id
    index_to_docstore_id={i: chunk_id for i, chunk_id in enumerate(df["chunk_id"])} # mapping for embeddings indexes to corresponding docs indexes
)

In [15]:
# save FAISS database

faiss_database = "data/faiss_database"
save_faiss_vector_store(vector_store, faiss_database)

FAISS vector store saved to 'data/faiss_database'.

In [16]:
vector_store = load_faiss_vector_store(faiss_database)

FAISS vector store loaded from 'data/faiss_database'.

In [17]:
# retriever for embeddings from FAISS database
faiss_retriever = vector_store.as_retriever(search_type="mmr", search_kwargs={"k": 5}) # top 5 documents

In [18]:
from langchain.retrievers import EnsembleRetriever

# hyrid retriever combining embeddings and keyword search
ensemble_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, faiss_retriever],
    weights=[0.5, 0.5]  # you can tune these weights
)

# Testing Sematic Search

In [19]:
query = "How to fill powder in the coffee machine"
results = ensemble_retriever.get_relevant_documents(query)

for i, doc in enumerate(results, 1):
    print(f"\nResult {i}")
    print(doc.page_content[:1000])  # show first 1000 chars

Result 1
bleshooting | 12
User manual SB1200
81
The aromas of the coffee beans evaporate in the bean hopper as a result of heat and air exchange. The
quality will have already deteriorated after 3 hours.
a) Coffee beans should not be moist.
b) Seal any open coffee bean packs in an airtight manner.
c) Do not store coffee beans in a refrigerator or freezer.
d) Only fill the coffee beans into the bean hopper that you will need for the next 3 hours.
12.4
Help with problems concerning product quality
Problem
Possible causes
Possible remedy
Coffee tastes stale
Grind too coarse
Select a finer grind Setting the grind
coarseness
Too little coffee
Increase coffee quantity Setting drinks
Temperature too low
Increase temperature Setting drinks
Coffee is old
Use fresh coffee
Bean hopper not locked correctly
Check locking of the bean hopper Filling
beans
Coffee tastes strange
Poor grind
Contact customer service
Minimal coffee usage
Pour a small amount of coffee beans into
the bean hopper
Spoiled coffee beans

Result 2
.
7.2
Filling beans
WARNING
Risk of injury
If objects find their way into the bean hopper or grinder, splinters may be ejected, leading to injury.
a) Never insert any objects into the bean hopper or grinder.
NOTICE
Poor beverage quality
The oil from the coffee beans is deposited on the inside of the bean hopper as a thin film of oil. This de-
posited oil ages quickly and impairs the taste of the beverages produced.
a) Remove the oil film from the inside of the bean hopper on a daily basis.
b) To do this, use a dry cloth or a cloth moistened only with water.
c) Do not use any cleaners, as these alter the taste of the coffee.
Fill the bean hopper with coffee beans.
Fill the powder hopper with powder suitable for automatic coffee makers.
1. Lift off the bean hopper lid.
2. Fill coffee beans.
Franke Kaffeemaschinen AG
Filling and emptying | 7
User manual SB1200
37
3. Fit the lid.
7.3
Filling powder
1. Lift off the powder hopper lid.
2. Fill with powder suitable for automatic bev-
erage dis

Result 3
 water tank/main water con-
nection coupling
If the error message appears while a
product is being dispensed, the brewing
module strainer is probably blocked
– Increase the grind coarseness and/or
reduce the grind quantity
– Remove the brewing module and
rinse it out
– Start the coffee machine cleaning
process
12 | Troubleshooting
Franke Kaffeemaschinen AG
82
User manual A1000
Error message/problem Possible cause
Measure
Touch screen not re-
sponding correctly
Overloaded machine software
There are two different troubleshooting
methods:
– Method 1: Press and hold the red but-
ton on the right-hand side of the op-
erator panel for 10 seconds to restart
– Method 2: Disconnect the coffee ma-
chine from the power grid. Wait
1 minute before reconnecting the cof-
fee machine to the power grid. Briefly
press the red button on the right-
hand side of the operator panel to
switch it on
12.3
Tips for good coffee beverages
NOTICE
Poor beverage quality
The oil from the coffee beans is deposited on

Result 4
 (12 l or 2 x 4.5 l)
MU
Milk pump module
FS60
Flavor Station with 6 flavor pumps
FSU60
Under-counter Flavor Station with 6 flavor pumps
CW
Cup warmer
FM
FoamMaster (cold and warm milk, cold and warm milk foam)
CM
CleanMaster
Twin
Modified cooling unit for the simultaneous use with two coffee machines
AC
Accounting system
CC
Coin changer
CL
Cashless
CV
Coin validator
Franke Kaffeemaschinen AG
Description of machine | 5
User manual A1000
21
5
DESCRIPTION OF MACHINE
5.1
Coffee machine
The A1000 coffee machine is available with numerous options. To provide you with an overview of your
machine, a sample configuration is illustrated here. Please note that your coffee machine may look differ-
ent from the configuration shown here.
Drip tray with drip grid
Insertion flap
Bean hopper
Hot water spout
Powder hopper (option)
Operator panel (10.4" touch
screen)
Spout with automatic height
adjustment
Steam wand (option)
Front door lock
with unlock button
5.1.1
Standard
– 10.4" touch screen
– One gri

Result 5
 Kaffeemaschinen AG
34
User manual A1000
3. Fit the lid.
7.3
Filling powder
1. Lift off the powder hopper lid.
2. Fill with powder suitable for automatic bev-
erage dispensers.
3. Fit the lid.
7.4
Filling the cooling unit
CAUTION
Germs in unpasteurized milk
Germs in unpasteurized milk could pose a health hazard.
a) Do not use any unpasteurized milk.
b) Only use pasteurized or long-life milk.
Franke Kaffeemaschinen AG
Filling and emptying | 7
User manual A1000
35
NOTICE
Machine damage
Using incorrect liquids can damage the machine.
a) Only fill the milk container with milk.
b) Use water and a mild cleaner to clean the milk container.
NOTICE
Spoiled milk
Insufficient cooling or hygiene can cause milk to spoil.
a) Only use precooled milk (2-5 °C).
b) Only store milk in the cooling unit during operating hours. Outside operating hours, e.g. overnight, store
the milk in a refrigerator.
c) Clean the machine and cooling unit once a day.
d) Only touch the suction hose, the inside of the milk co

Result 6
chiato
Chocolate
3. Select a product.
ð The preparation begins.
Caffè Crema To Go
Ristretto
Tea water
Chococcino
Espresso
Cappuccino
Double Espresso
Latte macchiato
Chocolate
4. Add more products to the queue list as
needed.
Caffè Crema To Go
Ristretto
Tea water
Chococcino
Espresso
Cappuccino
Double Espresso
Latte macchiato
Chocolate
5. Start the preparation of each of the products
in the queue list by pressing the green but-
ton.
ð The next preparation begins.
ð The product selection appears.
ð
All products are ready.
8.3
Preparing beverages with ground coffee
Only ground coffee may be used. Instant coffee made from dried coffee extract cannot be used.
1. Place an appropriate drinking vessel under
the dispensing spout.
2. Press the Decaffeinated coffee selection but-
ton.
Espresso
Double Espresso
Ristretto
Caffè Crema To Go
ð The Decaffeinated coffee selection button il-
luminates.
Franke Kaffeemaschinen AG
Preparing beverages | 8
User manual A1000
47
3. Open the insertion flap.
4. Fi

Result 7
 leading to injury.
a) Never insert any objects into the bean hopper or grinder.
CAUTION
Cutting injuries/crushing
The powder hoppers worm gear mechanism can cause cuts or crushing injuries.
a) Exercise care when cleaning the powder hopper.
1 | For your safety
Franke Kaffeemaschinen AG
10
User manual SB1200
CAUTION
Irritation from cleaners
Cleaning tablets, milk system cleaning agent, and descaler can lead to irritation of the skin or eyes.
a) Observe the hazard warnings on the label of the respective cleaner.
b) Avoid contact with your eyes and skin.
c) Wash your hands after coming into contact with cleaning supplies.
d) Cleaning supplies must be kept away from beverages.
CAUTION
Health hazard due to germ formation
Inadequate cleaning can result in food residues accumulating in the machine and at the spouts, thereby
contaminating products.
a) Do not use the machine unless it has been cleaned according to the instructions.
b) Clean the machine daily in accordance with the instructions.

Result 8
 on or off.
9.2
Required cleaning accessories
– Cleaning tablets
– Microfiber cloth
– Paint brush
– Brush set
– Spout cleaning device (if the hot water also comes from the central spout)
– Paper towel (for all-in-one spout)
9.3
5-step method
Clean the removable components of your coffee machine using the 5-step method. The display shows
you the components that can be removed during cleaning.
Clean the container and accessories of the cooling unit
Clean the containers and accessories, such as the lid, suction hose, suction nozzle, etc. using the 5-step
method.
1. Remove coarse dirt with a cleaning brush or
paint brush.
2. Soak the components in hot water with a
mild cleaner.
3. Wash the components.
4. Rinse the components thoroughly.
5. Dry the components.
Additional areas to be cleaned by hand
– Inner side of the door and door gasket on cooling unit
– Inner surfaces and shelf (if applicable) in the cooling chamber
9 | Cleaning
Franke Kaffeemaschinen AG
50
User manual A1000
– Interior,

Result 9
 using the automatic
Cleaning [} 49] function.
2. Empty the bean hopper and powder hopper.
3. Clean the bean hopper and powder hopper.
4. Clean the grounds container.
5. Empty the milk container.
6. Clean the milk container and container lid.
7. Clean the inside of the milk hose with a
brush.
8. Clean the suction filter with a twisted-in-wire
brush.
9. Clean the reversible adapter.
13.2
Back up data
Back up the data if the machine is to be recommissioned later or if the machine is to be replaced by a ma-
chine of the same type.
This manual applies to coffee machines without Franke Digital Services.
1. In the service menu under Customization and
data transfer, go to the menu item Go to Back
up/load data.
2. Go to Back up/load data.
3. Connect the USB stick and Select Export.
ð
The machine data and the configuration will
be saved on the USB stick.
4. Tap Yes to eject the USB stick after the
backup.
13.3
Short-term decommissioning (up to 3 weeks)
ü The machine remains in place.
1. Clean t

Result 10
 be impaired.
a) Push the locking slide all the way in.
7.9
Emptying the powder hopper
CAUTION
Cutting injuries/crushing
The powder hoppers worm gear mechanism can cause cuts or crushing injuries.
a) Exercise care when cleaning the powder hopper.
NOTICE
Contamination from powder
Powder can fall from the powder hopper.
a) Always transport the powder hopper in an upright position and ensure it is closed.
Franke Kaffeemaschinen AG
Filling and emptying | 7
User manual A1000
41
1. Pull the locking slide towards the front up to
the stop.
2. Lift and remove the powder hopper.
3. Empty, clean, and dry the powder hopper.
4. Attach the powder hopper.
5. Push the locking slide all the way in.
NOTICE
Impairment of function
If the bean hopper and powder hopper are not locked correctly, the function of the coffee machine and the
product quality may be impaired.
a) Push the locking slide all the way in.
7.10
Emptying the grounds container
NOTICE
Formation of mold
Coffee residue can lead to the format

/tmp/ipython-input-1504107448.py:2: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  results = ensemble_retriever.get_relevant_documents(query)

Without LLM

In [20]:
from ragas import SingleTurnSample
from ragas.metrics import NonLLMContextPrecisionWithReference

context_precision = NonLLMContextPrecisionWithReference()

retrieved_contexts = [doc.page_content for doc in results]

reference_text = """
1. Lift off the powder hopper lid.
2. Fill with powder suitable for automatic beverage dispensers.
3. Fit the lid.
"""

sample = SingleTurnSample(
    retrieved_contexts=retrieved_contexts,
    reference_contexts=[reference_text]
)

score = await context_precision.single_turn_ascore(sample)
print("Non-LLM context precision score:", score)

Non-LLM context precision score: 0.0

With LLM (using groq api)

In [22]:
from ragas import SingleTurnSample
from ragas.metrics import ContextPrecision
from ragas.llms import LangchainLLMWrapper
from langchain_groq import ChatGroq


langchain_llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0,
    groq_api_key="" #insert Api key
)
ragas_llm = LangchainLLMWrapper(langchain_llm)

context_precision = ContextPrecision(llm=ragas_llm)

retrieved_contexts = [doc.page_content for doc in results]

reference_text = """
1. Lift off the powder hopper lid.
2. Fill with powder suitable for automatic beverage dispensers.
3. Fit the lid.
"""

sample = SingleTurnSample(
    user_input=query,
    reference=reference_text,
    retrieved_contexts=retrieved_contexts
)

score = await context_precision.single_turn_ascore(sample)
print("LLM-based context precision score:", score)

LLM-based context precision score: 0.5453968253859175